
spring:
  application:
    name: snackmachine-app
  main:
    banner-mode: "OFF"
  datasource:
      driver-class-name: org.postgresql.Driver
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        maximumPoolSize: 30
        poolName: snackmachine-app
        minimumIdle: 5

server:
  port: 8000

