ALTER TABLE HEAD_OFFICE
DROP COLUMN HO_CASH_AMOUNT,
ADD COLUMN HO_ONE_CENT_COUNT INT,
ADD COLUMN HO_TEN_CENT_COUNT INT,
ADD COLUMN HO_QUARTER_CENT_COUNT INT,
ADD COLUMN HO_ONE_DOLLAR_COUNT INT,
ADD COLUMN HO_FIVE_DOLLAR_COUNT INT,
ADD COLUMN HO_TWENTY_DOLLAR_COUNT INT;