CREATE TABLE IF NOT EXISTS ATM_MACHINE
( AM_ID VARCHAR(255) NOT NULL,
  AM_AMOUNT_CHARGED NUMERIC(10,2),
  AM_ONE_CENT_COUNT INT,
  AM_TEN_CENT_COUNT INT,
  AM_QUARTER_CENT_COUNT INT,
  AM_ONE_DOLLAR_COUNT INT,
  AM_FIVE_DOLLAR_COUNT INT,
  AM_TWENTY_DOLLAR_COUNT INT,
  CONSTRAINT PK_ATM_MACHINE PRIMARY KEY (AM_ID));