CREATE TABLE IF NOT EXISTS SLOT
( SL_ID VARCHAR(255) NOT NULL,
  SL_SNACK_MACHINE_ID VARCHAR(255),
  SL_SNACK_ID VARCHAR(255),
  SL_QUANTITY INT NOT NULL,
  SL_POSITION SMALLINT NOT NULL,
  SL_PRICE DECIMAL NOT NULL,
  CONSTRAINT PK_SLOT PRIMARY KEY (SL_ID),
  CONSTRAINT FK_SLOT_SNACK_MACHINE FOREIGN KEY (SL_SNACK_MACHINE_ID) REFERENCES SNACK_MACHINE(SM_ID),
  CONSTRAINT FK_SLOT_SNACK FOREIGN KEY (SL_SNACK_ID) REFERENCES SNACK(S_ID))